### ISSUE TITLE
giving this after chat message

### ISSUE THREAD

**Issue by KakTak8D** [8Ball1337/openai-csgo-chatbot#1]
code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1659302991596,
    socket: 1659302991598,
    lookup: 1659302991703,
    connect: 1659302991861,
    secureConnect: 1659302992031,
    upload: 1659302992032,
    response: 1659302992216,
    end: 1659302992218,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 2,
      dns: 105,
      tcp: 158,
      tls: 170,
      request: 1,
      firstByte: 184,
      download: 2,
      total: 622
    }
  }
}

**Comment by 8Ball1337** [comment]
Is it possible that you don't have enough OpenAI credits or your trial credits expired?
I assume this error comes up when sending a request to OpenAI, right?
